ALTER TABLE tags ALTER COLUMN id TYPE BIGINT;
ALTER TABLE tags ALTER COLUMN board_id TYPE BIGINT;
ALTER TABLE card_tags ALTER COLUMN card_id TYPE BIGINT;
ALTER TABLE card_tags ALTER COLUMN tag_id TYPE BIGINT;
